### ISSUE TITLE
ERROR Cannot start nuxt:  Cannot read properties of undefined (reading 'nuxt')

### ISSUE THREAD

**Issue by d0peCode** [dulnan/nuxt-graphql-middleware#13]
Error:

>  ERROR  Cannot start nuxt:  Cannot read properties of undefined (reading 'nuxt')                         
  at graphqlMiddleware (node_modules/nuxt-graphql-middleware/dist/module.mjs:210:25)
  at installModule (node_modules/@nuxt/kit/dist/index.mjs:2426:101)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:3563:7)
  at async NuxtDevServer._load (node_modules/nuxi/dist/chunks/dev2.mjs:223:5)
  at async NuxtDevServer.load (node_modules/nuxi/dist/chunks/dev2.mjs:174:7)
  at async NuxtDevServer.init (node_modules/nuxi/dist/chunks/dev2.mjs:169:5)
  at async Object.run (node_modules/nuxi/dist/chunks/dev-child.mjs:105:5)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.89381a23.mjs:1647:7)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.89381a23.mjs:1638:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.89381a23.mjs:1770:7)

<img width="825" alt="image" src="https://github.com/dulnan/nuxt-graphql-middleware/assets/40339232/e56c35a9-11d0-4fce-b4de-ec1da2696528">

Steps to reproduce:

1. generate new nuxt3 app `npx nuxi@latest init <project-name>`
2. run `npm install --save nuxt-graphql-middleware`
3. add modules and example endpoint url to nuxt.config.ts:

```ts
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ['nuxt-graphql-middleware'],

  graphqlMiddleware: {
    graphqlEndpoint: 'https://example.com/graphql',
  }
})
```

4. run `npm run dev`

Reproduction repo: https://github.com/d0peCode/graph-middleware-issue

1. run `git clone https://github.com/d0peCode/graph-middleware-issue`
2. run `cd graph-middleware-issue/`
3. run `npm i` (fails at this point)

<img width="830" alt="image" src="https://github.com/dulnan/nuxt-graphql-middleware/assets/40339232/d07f553f-7892-4188-bdb7-069b2a546acb">

**Comment by dulnan** [comment]
This is because I messed up versions on NPM. Installing nuxt-graphql-middleware without a version installs 2.x which is only compatible with Nuxt 2.  It will be fixed once 4.0.0 is released. For the time being installing nuxt-graphql-middleware@beta will install the correct version for Nuxt 3.
